### ISSUE TITLE
Keeping the original file modified date

### ISSUE THREAD

**Issue by paolosupena** [hugsbrugs/php-sftp#7]
Hi!  First of all thanks for what you have did here. It's been pretty wonderful! Thank you for this work! 

Not really sure if this is a big issue for other people, so feel free to remove this post, if it seems in appropriate. 

I was just wondering if there was a way to preserve the original modified date of files uploaded using this library? 
We tested this library, and it was pretty great! It is just that in our project, we may need to preserve the original modified date. We were able to do it using plain FTP in the past, but had to switch to SFTP recently.

I was just wondering if this was possible or anyone might have already had encountered a need for it, before I fiddle with this more.

Thanks a lot!

**Comment by hugsbrugs** [comment]
Hey, thanks for your comment !

This lib is based on http://phpseclib.sourceforge.net/sftp/2.0/examples.html which supports SSH2 features http://phpseclib.sourceforge.net/ssh/intro.html

I can see in version 3 documentation https://phpseclib.com/docs/sftp#preserving-the-date the feature you're looking for : `$sftp->enableDatePreservation();` which in my opinion is also available in version 2 but can't find it in documentation.

So either you fork this lib and make your own either you make a pull request by adding this option as an optional parameter to `Sftp::upload` and `Sftp::upload_dir` functions !

cheers ;-)

**Comment by paolosupena** [comment]
Hi! Thanks for the insight. Looking at those docs, indeed it should be possible and very easy.  Thanks a lot!
